[package]
name = "pop65"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.*", features = ["derive", "wrap_help"] }

[dev-dependencies]
criterion = "0.5.*"

[[bench]]
name = "test_s"
harness = false
